# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfe2adaa2c6c8ee0ffdfd37ffc5f5e5faca58048eccbb6b1b796e76cf28d2194546eb3b88f94b752dc9910627935dd5d7ccd34dedb38b4554484e329e3704084

test:
  secret_key_base: 004492eb3c3ed7f5749eab3d28f4786c1af58984e434b843079369bd10641480e34688bfe0b30765ff5c61bd4c2d867c6dc142607599b494a5977ed4382179d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
